# Test against the latest version of this Node.js version
environment:
  nodejs_version: "14"

# Install scripts. (runs after repo cloning)
install:
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # run tests
  - npm test